/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main.content.account;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.CardLayout;
import java.io.File;
import java.io.UnsupportedEncodingException;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.Charset;
import java.nio.charset.CharsetEncoder;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.EnumMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import main.content.data.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import lib.DBHelper;
import main.content.home.Home;
import main.content.home.HomeAdmin;
import main.content.home.HomePetugas;

 /*
 * @author fahmi
 */
public class Account extends javax.swing.JInternalFrame {
    Connection connection = new DBHelper().init();
    String qrCodeData;

    String rpnama,rpuser,rppass;
    /**
     * Creates new form Data
     */
    String level;
    CardLayout cardLayout;
    public Account(String id,String level)  {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) getUI();
        ui.setNorthPane(null);
        this.level=level;
        String lev=this.level;
        cardLayout =(CardLayout)(cards.getLayout());      
        
        if("masyarakat".equals(lev)){
            cardLayout.show(cards, "card1");
            try {
                String sql1="select nama_lengkap,username,password from masyarakat where id_user='"+id+"'";
                ResultSet rs1=connection.createStatement().executeQuery(sql1);
                while (rs1.next()) {    
                    mnama.setText(rs1.getString(1));
                    musername.setText(rs1.getString(2));
                    this.rpnama = rs1.getString(1);
                    this.rpuser = rs1.getString(2);
                    this.rppass = rs1.getString(3);
                }
                result1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qr/qr1.png")));
                rs1.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }else if("petugas".equals(lev)){
            cardLayout.show(cards, "card2");
            try {
                String sql2="select nama_petugas,username,password from petugas where id_petugas='"+id+"'";
                ResultSet rs2=connection.createStatement().executeQuery(sql2);
                while (rs2.next()) {        
                    pnama.setText(rs2.getString(1));
                    pusername.setText(rs2.getString(2));
                    this.rpnama = rs2.getString(1);
                    this.rpuser = rs2.getString(2);
                    this.rppass = rs2.getString(3);                    
                }
                result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qr/qr.png")));
                rs2.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }else if("administrator".equals(lev)){
            cardLayout.show(cards, "card3");
            try {
                String sql3="select nama_petugas,username,password from petugas where id_petugas='"+id+"'";
                ResultSet rs3=connection.createStatement().executeQuery(sql3);
                while (rs3.next()) {   
                    anama.setText(rs3.getString(1));
                    pusername2.setText(rs3.getString(2));
                    this.rpnama = rs3.getString(1);
                    this.rpuser = rs3.getString(2);
                    this.rppass = rs3.getString(3);
                }
                result2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qr/qr2.png")));
                rs3.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cards = new javax.swing.JPanel();
        card2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnama = new javax.swing.JLabel();
        pusername = new javax.swing.JLabel();
        ppassword = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        card1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mnama = new javax.swing.JLabel();
        musername = new javax.swing.JLabel();
        ppassword1 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        card3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        anama = new javax.swing.JLabel();
        pusername2 = new javax.swing.JLabel();
        ppassword2 = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        cards.setBackground(java.awt.Color.white);
        cards.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cards.setPreferredSize(new java.awt.Dimension(887, 558));
        cards.setLayout(new java.awt.CardLayout());

        card2.setBackground(java.awt.Color.white);

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INFO AKUN PETUGAS");

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NAMA PETUGAS");

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("USERNAME");

        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("PASSWORD");

        pnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnama.setText("nama");

        pusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pusername.setText("username");

        ppassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppassword.setText("************");

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ppassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(pnama)
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(pusername)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(ppassword)
                .addGap(18, 18, 18)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        cards.add(card2, "card2");

        card1.setBackground(java.awt.Color.white);

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("INFO AKUN MASYARAKAT");

        jLabel12.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("NAMA PETUGAS");

        jLabel13.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("USERNAME");

        jLabel14.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PASSWORD");

        mnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnama.setText("nama");

        musername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        musername.setText("username");

        ppassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppassword1.setText("************");

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(musername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ppassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(62, 62, 62)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(mnama)
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(musername)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(ppassword1)
                .addGap(18, 18, 18)
                .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cards.add(card1, "card1");

        card3.setBackground(java.awt.Color.white);

        jLabel15.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(java.awt.Color.black);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("INFO AKUN ADMIN");

        jLabel16.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("NAMA PETUGAS");

        jLabel17.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("USERNAME");

        jLabel18.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PASSWORD");

        anama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anama.setText("nama");

        pusername2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pusername2.setText("username");

        ppassword2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppassword2.setText("***********");

        javax.swing.GroupLayout card3Layout = new javax.swing.GroupLayout(card3);
        card3.setLayout(card3Layout);
        card3Layout.setHorizontalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(anama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pusername2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ppassword2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
        );
        card3Layout.setVerticalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(62, 62, 62)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(anama)
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(pusername2)
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(ppassword2)
                .addGap(18, 18, 18)
                .addComponent(result2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cards.add(card3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anama;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel cards;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mnama;
    private javax.swing.JLabel musername;
    private javax.swing.JLabel pnama;
    private javax.swing.JLabel ppassword;
    private javax.swing.JLabel ppassword1;
    private javax.swing.JLabel ppassword2;
    private javax.swing.JLabel pusername;
    private javax.swing.JLabel pusername2;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel result2;
    // End of variables declaration//GEN-END:variables
}
